# Generated by Django 4.0.2 on 2022-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='my_blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
